global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using MonoGameLibrary;
global using MonoGameLibrary.Graphics;
global using MonoGameLibrary.Input;
global using System;
global using System.Collections.Generic;
global using System.Linq;
